tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "fzf"
brew "helm"
brew "htop"
brew "icdiff"
brew "kind"
brew "kubernetes-cli"
brew "ncdu"
brew "neovim"
brew "restic"
brew "tmux"
brew "tree"
brew "watch"
brew "zoxide"
cask "alacritty"
mas "Amphetamine", id: 937984704
mas "Magnet", id: 441258766
