---
- name: Install Packages
  hosts: all
  become: yes
  tasks:

    - name: Create Keyrings Directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Add EZA Repository Key
      apt_key:
        url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
        state: present
        keyring: /etc/apt/keyrings/gierens.gpg

    - name: Add EZA Repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main"
        state: present
        filename: gierens

    - name: Add Fish Shell Repository Key
      apt_key:
        url: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_10/Release.key
        state: present

    - name: Add Fish Shell Repository
      apt_repository:
        repo: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10/ /"
        state: present
        filename: shells-fish-release-3

    - name: Update Package Cache & Install Packages
      apt:
        name:
          - eza
          - fish
          - fzf
          - git
          - neovim
          - tmux
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade Packages
      apt: 
        upgrade: yes
        autoremove: yes
        autoclean: yes
