---
- name: Install Packages
  import_playbook: 1-install-packages.yml

- name: Install Dotfiles
  import_playbook: 2-install-dotfiles.yml

- name: Install Nerd Fonts
  import_playbook: 3-install-nerd-fonts.yml

- name: Install Starship
  import_playbook: 4-install-starship.yml

- name: Install Fish Shell
  import_playbook: 5-install-fish-shell.yml

- name: Install Tmux
  import_playbook: 6-install-tmux.yml
